### ISSUE TITLE
Gutenberg now detects automated downloads

### ISSUE THREAD

**Issue by joja19** [motoom/gutenberg-ebook-scraping#1]
Hi Motoom,

 Thanks for the scripts, but gutenberg.org now detects automated downloads. As I don't understand Dutch, I changed the link in bulkdownload.py to "http://www.gutenberg.org/browse/scores/top" and only one book was downloaded, it is "Lord Tedric, 49503-8.txt". The reset of the fetched TXT files were indeed HTML source of a page complaining that I downloaded too many times from gutenberg.org today and to verify that I am human, I must fill in a captcha. 

I hope this could be circumvented in the future.

**Comment by motoom** [comment]
I have fixed this. The program now downloads from a mirror archive, not from the Gutenberg main web site.
